<Project>
  <PropertyGroup>
    <ProjectFolderName>$(MSBuildProjectName)</ProjectFolderName>

    <RepositoryRoot Condition="'$(SolutionDir)' == ''">$(MSBuildThisFileDirectory)</RepositoryRoot>
    <RepositoryRoot Condition="'$(SolutionDir)' != ''">$(SolutionDir)</RepositoryRoot>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <BaseOutputPath>$(RepositoryRoot)bin</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RepositoryRoot)obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
