//
// :.:.:.:.:.
// GWC.Native
// v0.3.3
// :.:.:.:.:.
//
// https://github.com/reallukee/gwc
//
// KEYS.h
//  Licenza MIT
//

#pragma once

#ifndef GWC_KEYS_H
#define GWC_KEYS_H

#include "header.h"

typedef enum gKEYS
{
    KEYS_NONE               = 0,
    KEYS_LBUTTON            = 1,
    KEYS_RBUTTON            = 2,
    KEYS_CANCEL             = 3,
    KEYS_MBUTTON            = 4,
    KEYS_XBUTTON1           = 5,
    KEYS_XBUTTON2           = 6,
    KEYS_BACK               = 8,
    KEYS_TAB                = 9,
    KEYS_LINEFEED           = 10,
    KEYS_CLEAR              = 12,
    KEYS_RETURN             = 13,
    KEYS_SHIFTKEY           = 16,
    KEYS_CONTROLKEY         = 17,
    KEYS_MENU               = 18,
    KEYS_PAUSE              = 19,
    KEYS_CAPITAL            = 20,
    KEYS_KANAMODE           = 21,
    KEYS_JUNJAMODE          = 23,
    KEYS_FINALMODE          = 24,
    KEYS_HANJAMODE          = 25,
    KEYS_ESCAPE             = 27,
    KEYS_IMECONVERT         = 28,
    KEYS_IMENONCONVERT      = 29,
    KEYS_IMEACEEPT          = 30,
    KEYS_IMEMODECHANGE      = 31,
    KEYS_SPACE              = 32,
    KEYS_PAGEUP             = 33,
    KEYS_NEXT               = 34,
    KEYS_END                = 35,
    KEYS_HOME               = 36,
    KEYS_LEFT               = 37,
    KEYS_UP                 = 38,
    KEYS_RIGHT              = 39,
    KEYS_DOWN               = 40,
    KEYS_SELECT             = 41,
    KEYS_PRINT              = 42,
    KEYS_EXECUTE            = 43,
    KEYS_PRINTSCREEN        = 44,
    KEYS_INSERT             = 45,
    KEYS_DELETE             = 46,
    KEYS_HELP               = 47,
    KEYS_D0                 = 48,
    KEYS_D1                 = 49,
    KEYS_D2                 = 50,
    KEYS_D3                 = 51,
    KEYS_D4                 = 52,
    KEYS_D5                 = 53,
    KEYS_D6                 = 54,
    KEYS_D7                 = 55,
    KEYS_D8                 = 56,
    KEYS_D9                 = 57,
    KEYS_A                  = 65,
    KEYS_B                  = 66,
    KEYS_C                  = 67,
    KEYS_D                  = 68,
    KEYS_E                  = 69,
    KEYS_F                  = 70,
    KEYS_G                  = 71,
    KEYS_H                  = 72,
    KEYS_I                  = 73,
    KEYS_J                  = 74,
    KEYS_K                  = 75,
    KEYS_L                  = 76,
    KEYS_M                  = 77,
    KEYS_N                  = 78,
    KEYS_O                  = 79,
    KEYS_P                  = 80,
    KEYS_Q                  = 81,
    KEYS_R                  = 82,
    KEYS_S                  = 83,
    KEYS_T                  = 84,
    KEYS_U                  = 85,
    KEYS_V                  = 86,
    KEYS_W                  = 87,
    KEYS_X                  = 88,
    KEYS_Y                  = 89,
    KEYS_Z                  = 90,
    KEYS_LWIN               = 91,
    KEYS_RWIN               = 92,
    KEYS_APPS               = 93,
    KEYS_SLEEP              = 95,
    KEYS_NUMPAD0            = 96,
    KEYS_NUMPAD1            = 97,
    KEYS_NUMPAD2            = 98,
    KEYS_NUMPAD3            = 99,
    KEYS_NUMPAD4            = 100,
    KEYS_NUMPAD5            = 101,
    KEYS_NUMPAD6            = 102,
    KEYS_NUMPAD7            = 103,
    KEYS_NUMPAD8            = 104,
    KEYS_NUMPAD9            = 105,
    KEYS_MULTIPLY           = 106,
    KEYS_ADD                = 107,
    KEYS_SEPARATOR          = 108,
    KEYS_SUBTRACT           = 109,
    KEYS_DECIMAL            = 110,
    KEYS_DIVIDE             = 111,
    KEYS_F1                 = 112,
    KEYS_F2                 = 113,
    KEYS_F3                 = 114,
    KEYS_F4                 = 115,
    KEYS_F5                 = 116,
    KEYS_F6                 = 117,
    KEYS_F7                 = 118,
    KEYS_F8                 = 119,
    KEYS_F9                 = 120,
    KEYS_F10                = 121,
    KEYS_F11                = 122,
    KEYS_F12                = 123,
    KEYS_F13                = 124,
    KEYS_F14                = 125,
    KEYS_F15                = 126,
    KEYS_F16                = 127,
    KEYS_F17                = 128,
    KEYS_F18                = 129,
    KEYS_F19                = 130,
    KEYS_F20                = 131,
    KEYS_F21                = 132,
    KEYS_F22                = 133,
    KEYS_F23                = 134,
    KEYS_F24                = 135,
    KEYS_NUMLOCK            = 144,
    KEYS_SCROLL             = 145,
    KEYS_LSHIFTKEY          = 160,
    KEYS_RSHIFTKEY          = 161,
    KEYS_LCONTROLKEY        = 162,
    KEYS_RCONTROLKEY        = 163,
    KEYS_LMENU              = 164,
    KEYS_RMENU              = 165,
    KEYS_BROWSERBACK        = 166,
    KEYS_BROWSERFORWARD     = 167,
    KEYS_BROWSERREFRESH     = 168,
    KEYS_BROWSERSTOP        = 169,
    KEYS_BROWSERSEARCH      = 170,
    KEYS_BROWSERFAVORITES   = 171,
    KEYS_BROWSERHOME        = 172,
    KEYS_VOLUMEMUTE         = 173,
    KEYS_VOLUMEDOWN         = 174,
    KEYS_VOLUMEUP           = 175,
    KEYS_MEDIANEXTTRACK     = 176,
    KEYS_MEDIAPREVIOUSTRACK = 177,
    KEYS_MEDIASTOP          = 178,
    KEYS_MEDIAPLAYPAUSE     = 179,
    KEYS_LAUNCHMAIL         = 180,
    KEYS_SELECTMEDIA        = 181,
    KEYS_LAUNCHAPPLICATION1 = 182,
    KEYS_LAUNCHAPPLICATION2 = 183,
    KEYS_OEM1               = 186,
    KEYS_OEMPLUS            = 187,
    KEYS_OEMCOMMA           = 188,
    KEYS_OEMMINUS           = 189,
    KEYS_OEMPERIOD          = 190,
    KEYS_OEMQUESTION        = 191,
    KEYS_OEMTILDE           = 192,
    KEYS_OEMOPENBRACKETS    = 219,
    KEYS_OEM5               = 220,
    KEYS_OEM6               = 221,
    KEYS_OEM7               = 222,
    KEYS_OEM8               = 223,
    KEYS_OEMBACKSLASH       = 226,
    KEYS_PROCESSKEY         = 229,
    KEYS_PACKET             = 231,
    KEYS_ATTN               = 246,
    KEYS_CRSEL              = 247,
    KEYS_EXSEL              = 248,
    KEYS_ERASEEOF           = 249,
    KEYS_PLAY               = 250,
    KEYS_ZOOM               = 251,
    KEYS_NONAME             = 252,
    KEYS_PA1                = 253,
    KEYS_OEMCLEAR           = 254,
    KEYS_KEYCODE            = 65535,
    KEYS_SHIFT              = 65536,
    KEYS_CONTROL            = 131072,
    KEYS_ALT                = 262144,
    KEYS_MODIFIERS          = -65536,
} gKEYS;

#endif // !GWC_KEYS_H
