//
// :.:.:.:.:.
// GWC.Native
// v0.3.3
// :.:.:.:.:.
//
// https://github.com/reallukee/gwc
//
// KEYS.h
//  Licenza MIT
//

#pragma once

#ifndef GWC_KEYS_H
#define GWC_KEYS_H

#include "header.h"

typedef enum gKEYS
{
    gKEYS_NONE               = 0,
    gKEYS_LBUTTON            = 1,
    gKEYS_RBUTTON            = 2,
    gKEYS_CANCEL             = 3,
    gKEYS_MBUTTON            = 4,
    gKEYS_XBUTTON1           = 5,
    gKEYS_XBUTTON2           = 6,
    gKEYS_BACK               = 8,
    gKEYS_TAB                = 9,
    gKEYS_LINEFEED           = 10,
    gKEYS_CLEAR              = 12,
    gKEYS_RETURN             = 13,
    gKEYS_SHIFTKEY           = 16,
    gKEYS_CONTROLKEY         = 17,
    gKEYS_MENU               = 18,
    gKEYS_PAUSE              = 19,
    gKEYS_CAPITAL            = 20,
    gKEYS_KANAMODE           = 21,
    gKEYS_JUNJAMODE          = 23,
    gKEYS_FINALMODE          = 24,
    gKEYS_HANJAMODE          = 25,
    gKEYS_ESCAPE             = 27,
    gKEYS_IMECONVERT         = 28,
    gKEYS_IMENONCONVERT      = 29,
    gKEYS_IMEACEEPT          = 30,
    gKEYS_IMEMODECHANGE      = 31,
    gKEYS_SPACE              = 32,
    gKEYS_PAGEUP             = 33,
    gKEYS_NEXT               = 34,
    gKEYS_END                = 35,
    gKEYS_HOME               = 36,
    gKEYS_LEFT               = 37,
    gKEYS_UP                 = 38,
    gKEYS_RIGHT              = 39,
    gKEYS_DOWN               = 40,
    gKEYS_SELECT             = 41,
    gKEYS_PRINT              = 42,
    gKEYS_EXECUTE            = 43,
    gKEYS_PRINTSCREEN        = 44,
    gKEYS_INSERT             = 45,
    gKEYS_DELETE             = 46,
    gKEYS_HELP               = 47,
    gKEYS_D0                 = 48,
    gKEYS_D1                 = 49,
    gKEYS_D2                 = 50,
    gKEYS_D3                 = 51,
    gKEYS_D4                 = 52,
    gKEYS_D5                 = 53,
    gKEYS_D6                 = 54,
    gKEYS_D7                 = 55,
    gKEYS_D8                 = 56,
    gKEYS_D9                 = 57,
    gKEYS_A                  = 65,
    gKEYS_B                  = 66,
    gKEYS_C                  = 67,
    gKEYS_D                  = 68,
    gKEYS_E                  = 69,
    gKEYS_F                  = 70,
    gKEYS_G                  = 71,
    gKEYS_H                  = 72,
    gKEYS_I                  = 73,
    gKEYS_J                  = 74,
    gKEYS_K                  = 75,
    gKEYS_L                  = 76,
    gKEYS_M                  = 77,
    gKEYS_N                  = 78,
    gKEYS_O                  = 79,
    gKEYS_P                  = 80,
    gKEYS_Q                  = 81,
    gKEYS_R                  = 82,
    gKEYS_S                  = 83,
    gKEYS_T                  = 84,
    gKEYS_U                  = 85,
    gKEYS_V                  = 86,
    gKEYS_W                  = 87,
    gKEYS_X                  = 88,
    gKEYS_Y                  = 89,
    gKEYS_Z                  = 90,
    gKEYS_LWIN               = 91,
    gKEYS_RWIN               = 92,
    gKEYS_APPS               = 93,
    gKEYS_SLEEP              = 95,
    gKEYS_NUMPAD0            = 96,
    gKEYS_NUMPAD1            = 97,
    gKEYS_NUMPAD2            = 98,
    gKEYS_NUMPAD3            = 99,
    gKEYS_NUMPAD4            = 100,
    gKEYS_NUMPAD5            = 101,
    gKEYS_NUMPAD6            = 102,
    gKEYS_NUMPAD7            = 103,
    gKEYS_NUMPAD8            = 104,
    gKEYS_NUMPAD9            = 105,
    gKEYS_MULTIPLY           = 106,
    gKEYS_ADD                = 107,
    gKEYS_SEPARATOR          = 108,
    gKEYS_SUBTRACT           = 109,
    gKEYS_DECIMAL            = 110,
    gKEYS_DIVIDE             = 111,
    gKEYS_F1                 = 112,
    gKEYS_F2                 = 113,
    gKEYS_F3                 = 114,
    gKEYS_F4                 = 115,
    gKEYS_F5                 = 116,
    gKEYS_F6                 = 117,
    gKEYS_F7                 = 118,
    gKEYS_F8                 = 119,
    gKEYS_F9                 = 120,
    gKEYS_F10                = 121,
    gKEYS_F11                = 122,
    gKEYS_F12                = 123,
    gKEYS_F13                = 124,
    gKEYS_F14                = 125,
    gKEYS_F15                = 126,
    gKEYS_F16                = 127,
    gKEYS_F17                = 128,
    gKEYS_F18                = 129,
    gKEYS_F19                = 130,
    gKEYS_F20                = 131,
    gKEYS_F21                = 132,
    gKEYS_F22                = 133,
    gKEYS_F23                = 134,
    gKEYS_F24                = 135,
    gKEYS_NUMLOCK            = 144,
    gKEYS_SCROLL             = 145,
    gKEYS_LSHIFTKEY          = 160,
    gKEYS_RSHIFTKEY          = 161,
    gKEYS_LCONTROLKEY        = 162,
    gKEYS_RCONTROLKEY        = 163,
    gKEYS_LMENU              = 164,
    gKEYS_RMENU              = 165,
    gKEYS_BROWSERBACK        = 166,
    gKEYS_BROWSERFORWARD     = 167,
    gKEYS_BROWSERREFRESH     = 168,
    gKEYS_BROWSERSTOP        = 169,
    gKEYS_BROWSERSEARCH      = 170,
    gKEYS_BROWSERFAVORITES   = 171,
    gKEYS_BROWSERHOME        = 172,
    gKEYS_VOLUMEMUTE         = 173,
    gKEYS_VOLUMEDOWN         = 174,
    gKEYS_VOLUMEUP           = 175,
    gKEYS_MEDIANEXTTRACK     = 176,
    gKEYS_MEDIAPREVIOUSTRACK = 177,
    gKEYS_MEDIASTOP          = 178,
    gKEYS_MEDIAPLAYPAUSE     = 179,
    gKEYS_LAUNCHMAIL         = 180,
    gKEYS_SELECTMEDIA        = 181,
    gKEYS_LAUNCHAPPLICATION1 = 182,
    gKEYS_LAUNCHAPPLICATION2 = 183,
    gKEYS_OEM1               = 186,
    gKEYS_OEMPLUS            = 187,
    gKEYS_OEMCOMMA           = 188,
    gKEYS_OEMMINUS           = 189,
    gKEYS_OEMPERIOD          = 190,
    gKEYS_OEMQUESTION        = 191,
    gKEYS_OEMTILDE           = 192,
    gKEYS_OEMOPENBRACKETS    = 219,
    gKEYS_OEM5               = 220,
    gKEYS_OEM6               = 221,
    gKEYS_OEM7               = 222,
    gKEYS_OEM8               = 223,
    gKEYS_OEMBACKSLASH       = 226,
    gKEYS_PROCESSKEY         = 229,
    gKEYS_PACKET             = 231,
    gKEYS_ATTN               = 246,
    gKEYS_CRSEL              = 247,
    gKEYS_EXSEL              = 248,
    gKEYS_ERASEEOF           = 249,
    gKEYS_PLAY               = 250,
    gKEYS_ZOOM               = 251,
    gKEYS_NONAME             = 252,
    gKEYS_PA1                = 253,
    gKEYS_OEMCLEAR           = 254,
    gKEYS_KEYCODE            = 65535,
    gKEYS_SHIFT              = 65536,
    gKEYS_CONTROL            = 131072,
    gKEYS_ALT                = 262144,
    gKEYS_MODIFIERS          = -65536,
} gKEYS;

#endif // !GWC_KEYS_H
